blank_issues_enabled: false
contact_links:
  - name: Local AI Community
    url: https://thinktank.ottomator.ai/c/local-ai/18
    about: Please ask questions and start conversations about the Local AI Package here in the oTTomator Think Tank!